In [59]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model 
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import *

In [66]:
df_price = pd.read_csv('data/price_availability.csv', sep=';')
df_listing = pd.read_csv('data/listings_final.csv', sep=';')
print('data loaded')

data loaded


In [69]:
df_price

listing_id         day                       created  available  \
0           9810829  2018-12-08  2018-09-27 06:14:10.000+0000       True   
1           9810829  2018-12-08  2018-09-26 19:34:02.000+0000       True   
2          20897010  2018-12-09  2018-09-27 10:38:57.000+0000       True   
3          20897010  2018-12-09  2018-09-27 06:10:27.000+0000       True   
4          20897010  2018-12-09  2018-09-26 19:30:25.000+0000       True   
...             ...         ...                           ...        ...   
4748691    23608395  2018-09-06  2018-09-27 06:05:42.000+0000      False   
4748692    23608395  2018-09-06  2018-09-26 19:31:32.000+0000      False   
4748693     1447132  2018-12-27  2018-09-27 10:46:16.000+0000      False   
4748694     1447132  2018-12-27  2018-09-27 06:07:36.000+0000      False   
4748695     1447132  2018-12-27  2018-09-26 19:37:40.000+0000      False   

        local_currency  local_price  min_nights  
0                  EUR          160           1  
1                  EUR          160           1  
2                  EUR          172           2  
3                  EUR          172           2  
4                  EUR          172           2  
...                ...          ...         ...  
4748691            EUR           24           1  
4748692            EUR           24           1  
4748693            EUR          125           3  
4748694            EUR          125           3  
4748695            EUR          125           3  

[4748696 rows x 7 columns]

In [70]:
df_listing

Unnamed: 0  listing_id                                      name  \
0             0    28581061                           La maison Clery   
1             1      661961       studio PARIS PLACE EDITH PIAF 75020   
2             2     1261705  chambre privée à louer @ paris oberkampf   
3             3     1318834            Appartement au coeur du Marais   
4             4     1677091                       Lovely & Quiet flat   
..          ...         ...                                       ...   
995         995    28335197          Studio cosy Jardin du Luxembourg   
996         996    28583013    Charmant  30m2 - Faubourg Saint Martin   
997         997    28628316       Cosy flat in the marais - Best area   
998         998    28792796         Appartement 3 chambres madeleine.   
999         999    28682896                          Village Jourdain   

             type   city                    neighborhood   latitude  \
0    private_room  Paris               2e arrondissement  48.869292   
1     entire_home  Paris                             NaN  48.867284   
2    private_room  Paris                             NaN  48.867894   
3     entire_home  Paris                      République  48.870370   
4     entire_home  Paris    Buttes-Chaumont - Belleville  48.874149   
..            ...    ...                             ...        ...   
995   entire_home  Paris  Saint Germain des Prés - Odéon  48.848695   
996   entire_home  Paris                      République  48.871623   
997   entire_home  Paris               2e arrondissement  48.867434   
998   entire_home  Paris             Madeleine - Vendôme  48.870109   
999  private_room  Paris    Buttes-Chaumont - Belleville  48.875425   

     longitude  person_capacity  beds  bedrooms  bathrooms  is_rebookable  \
0     2.348335                1     1         1        2.0          False   
1     2.403255                2     1         1        1.0          False   
2     2.375897                1     1         1        1.0          False   
3     2.358510                3     2         2        1.0          False   
4     2.373700                2     1         1        1.0          False   
..         ...              ...   ...       ...        ...            ...   
995   2.325857                2     1         0        1.0          False   
996   2.358006                3     1         1        1.0          False   
997   2.351771                4     2         1        1.0          False   
998   2.321475                6     4         2        1.5          False   
999   2.395240                2     1         1        1.0          False   

     is_new_listing  is_fully_refundable  is_host_highly_rated  \
0              True                 True                 False   
1             False                 True                  True   
2             False                 True                  True   
3             False                 True                 False   
4             False                 True                  True   
..              ...                  ...                   ...   
995            True                 True                 False   
996            True                 True                 False   
997            True                 True                  True   
998            True                 True                 False   
999            True                 True                 False   

     is_business_travel_ready  pricing_weekly_factor  pricing_monthly_factor  
0                       False                   1.00                    1.00  
1                       False                   0.88                    0.69  
2                       False                   1.00                    1.00  
3                       False                   0.82                    0.48  
4                       False                   0.95                    0.90  
..                        ...                    ...                     ...  
995 

In [74]:
df_price = df_price.groupby(['listing_id']).mean()
df_listing = df_listing.groupby(['listing_id']).mean()
print("mean group by ok")

mean group by ok


In [75]:
df_price

available  local_price  min_nights
listing_id                                    
5396         0.011494   102.363985    2.000000
7397         0.168297   110.107632   11.000000
9342         0.309198   396.863014    2.784736
10010        0.254593   136.154856    4.955381
10270        0.511688   105.779221    4.937662
...               ...          ...         ...
28836096     0.082707   321.428571    1.022556
28838519     0.083333    54.483333    5.000000
28840013     0.743083   112.122530    2.000000
28846494     0.225564   168.037594    4.000000
28851976     0.812030   128.000000    2.000000

[11749 rows x 3 columns]

In [76]:
df_listing

Unnamed: 0   latitude  longitude  person_capacity  beds  bedrooms  \
listing_id                                                                      
56093               12  48.867284   2.358431                4     2         1   
57207               13  48.846184   2.304455                2     1         1   
114543              19  48.849530   2.290219                2     1         1   
149534               9  48.866360   2.361844                4     2         1   
164255              28  48.861398   2.364299                4     2         1   
...                ...        ...        ...              ...   ...       ...   
28684174           662  48.879223   2.292382                5     0         1   
28709644           745  48.872202   2.298349                4     2         1   
28751412            88  48.880923   2.314568                2     1         0   
28774896           159  48.852915   2.314519                2     1         1   
28792796           998  48.870109   2.321475                6     4         2   

            bathrooms  is_rebookable  is_new_listing  is_fully_refundable  \
listing_id                                                                  
56093             1.0          False           False                 True   
57207             1.0          False           False                 True   
114543            1.0          False           False                 True   
149534            1.0          False           False                 True   
164255            1.0          False           False                 True   
...               ...            ...             ...                  ...   
28684174          1.0          False            True                 True   
28709644          1.0          False            True                 True   
28751412          1.0          False            True                 True   
28774896          1.0          False            True                 True   
28792796          1.5          False            True                 True   

            is_host_highly_rated  is_business_travel_ready  \
listing_id                                                   
56093                       True                     False   
57207                      False                     False   
114543                      True                     False   
149534                      True                     False   
164255                     False                     False   
...                          ...                       ...   
28684174                   False                     False   
28709644                   False                     False   
28751412                   False                     False   
28774896                   False                     False   
28792796                   False                     False   

            pricing_weekly_factor  pricing_monthly_factor  
listing_id                                                 
56093                        0.88                     1.0  
57207                        0.87                     1.0  
114543                       0.90                     0.9  
149534                       1.00                     0.4  
164255                       1.00                     1.0  
...                           ...                     ...  
28684174                     1.00                     1.0  
28709644                     1.00                     1.0  
28751412                     1.00                     1.0  
28774896                     1.00                     1.0  
28792796                     1.00                     1.0  

[1000 rows x 14 columns]

In [78]:
df_global = pd.merge(df_price[['local_price']], df_listing, on=['listing_id'])
df_global

local_price  Unnamed: 0   latitude  longitude  person_capacity  \
listing_id                                                                   
56093        170.000000          12  48.867284   2.358431                4   
57207         49.952756          13  48.846184   2.304455                2   
114543       107.374026          19  48.849530   2.290219                2   
149534       169.000000           9  48.866360   2.361844                4   
164255        75.876209          28  48.861398   2.364299                4   
...                 ...         ...        ...        ...              ...   
28684174     725.175781         662  48.879223   2.292382                5   
28709644     475.000000         745  48.872202   2.298349                4   
28751412     117.000000          88  48.880923   2.314568                2   
28774896     156.397468         159  48.852915   2.314519                2   
28792796      49.184211         998  48.870109   2.321475                6   

            beds  bedrooms  bathrooms  is_rebookable  is_new_listing  \
listing_id                                                             
56093          2         1        1.0          False           False   
57207          1         1        1.0          False           False   
114543         1         1        1.0          False           False   
149534         2         1        1.0          False           False   
164255         2         1        1.0          False           False   
...          ...       ...        ...            ...             ...   
28684174       0         1        1.0          False            True   
28709644       2         1        1.0          False            True   
28751412       1         0        1.0          False            True   
28774896       1         1        1.0          False            True   
28792796       4         2        1.5          False            True   

            is_fully_refundable  is_host_highly_rated  \
listing_id                                              
56093                      True                  True   
57207                      True                 False   
114543                     True                  True   
149534                     True                  True   
164255                     True                 False   
...                         ...                   ...   
28684174                   True                 False   
28709644                   True                 False   
28751412                   True                 False   
28774896                   True                 False   
28792796                   True                 False   

            is_business_travel_ready  pricing_weekly_factor  \
listing_id                                                    
56093                          False                   0.88   
57207                          False                   0.87   
114543                         False                   0.90   
149534                         False                   1.00   
164255                         False                   1.00   
...                              ...                    ...   
28684174                       False                   1.00   
28709644                       False                   1.00   
28751412                       False                   1.00   
28774896                       False                   1.00   
28792796                       False                   1.00   

            pricing_monthly_factor  
listing_id                          
56093                          1.0  
57207                          1.0  
114543                         0.9  
149534                         0.4  
164255                         1.0  
...                            ...  
28684174                       1.0  
28709644                       1.0  
28751412                       1.0  
28774896                       1.0  
28792796                       1.0  

[999 rows x 15 c

In [84]:
y = df_global[["local_price"]]
x = df_global[["person_capacity","beds","bedrooms","bathrooms"]]

In [85]:
y = np.array(y)
x = np.array(x)

In [86]:
y

array([[ 170.        ],
       [  49.95275591],
       [ 107.37402597],
       [ 169.        ],
       [  75.8762089 ],
       [ 284.35356201],
       [  36.58961039],
       [ 300.        ],
       [ 101.37984496],
       [  67.20833333],
       [  60.74093264],
       [  38.        ],
       [  92.        ],
       [  66.21204188],
       [  79.68041237],
       [  90.09819121],
       [ 170.        ],
       [ 115.7544757 ],
       [ 283.76115486],
       [ 144.74424552],
       [ 347.67015707],
       [ 115.        ],
       [ 105.        ],
       [ 154.65384615],
       [ 380.        ],
       [  44.16569201],
       [ 233.69170984],
       [ 146.        ],
       [ 147.96623377],
       [ 105.        ],
       [ 163.47286822],
       [ 190.        ],
       [ 180.95287958],
       [ 128.8630491 ],
       [  44.47368421],
       [ 163.28571429],
       [  94.        ],
       [  94.97619048],
       [ 218.96373057],
       [ 234.89460154],
       [ 300.78640777],
       [  62.   

In [87]:
X

person_capacity  beds  bedrooms  bathrooms
0                  1     1         1        2.0
1                  2     1         1        1.0
2                  1     1         1        1.0
3                  3     2         2        1.0
4                  2     1         1        1.0
..               ...   ...       ...        ...
995                2     1         0        1.0
996                3     1         1        1.0
997                4     2         1        1.0
998                6     4         2        1.5
999                2     1         1        1.0

[1000 rows x 4 columns]

In [106]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)
x_train

array([[4. , 2. , 1. , 1. ],
       [2. , 1. , 1. , 1. ],
       [6. , 4. , 3. , 1.5],
       ...,
       [4. , 2. , 2. , 1. ],
       [5. , 1. , 1. , 1. ],
       [2. , 1. , 1. , 1. ]])

In [107]:
x_train.shape 

(699, 4)

In [108]:
x_test.shape 

(300, 4)

In [109]:
y_train.shape 

(699, 1)

In [110]:
y_test.shape 

(300, 1)

In [115]:
linreg = linear_model.LinearRegression().fit(x_train, y_train)
linreg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [122]:
linreg.coef_

array([[ 36.20879253, -26.20790472,  27.52192177,  95.59654916]])

In [124]:
linreg.intercept_

array([-46.69756447])

In [178]:
y_pred = linreg.predict(x_test)
y_pred

array([[ 134.22006884],
       [ 571.22728396],
       [ 122.63058679],
       [ 180.15517198],
       [  95.10866502],
       [ 339.48243544],
       [  96.42268207],
       [-306.69677656],
       [ 122.63058679],
       [ 546.60797348],
       [ 196.3621889 ],
       [  95.10866502],
       [ 329.48154763],
       [ 168.84026713],
       [ 170.42886137],
       [ 242.57186924],
       [ 196.3621889 ],
       [ 168.84026713],
       [ 329.48154763],
       [ 216.63854171],
       [ 122.63058679],
       [ 122.63058679],
       [ 392.7903923 ],
       [ 122.63058679],
       [ 122.63058679],
       [ 311.96051367],
       [ 168.84026713],
       [  95.10866502],
       [ 141.31834536],
       [ 122.63058679],
       [  95.10866502],
       [ 132.6314746 ],
       [ 141.31834536],
       [ 243.88588628],
       [  95.10866502],
       [ 168.84026713],
       [  96.42268207],
       [ 291.95873806],
       [ 285.75260895],
       [  95.10866502],
       [ 122.63058679],
       [ 122.630

In [179]:
mean_squared_error(y_test, y_pred)

20361.84416948426

In [180]:
r2_score(y_test, y_pred)

0.41298243967788906